/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DesaparecidosRouteImport } from './routes/desaparecidos'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as DoadoresIndexRouteImport } from './routes/doadores.index'
import { Route as DoadoresDoadorIdRouteImport } from './routes/doadores.$doadorId'
import { Route as VaquinhasIndexRouteImport } from './routes/vaquinhas.index'
import { Route as VaquinhasVaquinhaIdRouteImport } from './routes/vaquinhas.$vaquinhaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaparecidosRoute = DesaparecidosRouteImport.update({
  id: '/desaparecidos',
  path: '/desaparecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const DoadoresIndexRoute = DoadoresIndexRouteImport.update({
  id: '/doadores/',
  path: '/doadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoadoresDoadorIdRoute = DoadoresDoadorIdRouteImport.update({
  id: '/doadores/$doadorId',
  path: '/doadores/$doadorId',
  getParentRoute: () => rootRouteImport,
} as any)
const VaquinhasIndexRoute = VaquinhasIndexRouteImport.update({
  id: '/vaquinhas/',
  path: '/vaquinhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaquinhasVaquinhaIdRoute = VaquinhasVaquinhaIdRouteImport.update({
  id: '/vaquinhas/$vaquinhaId',
  path: '/vaquinhas/$vaquinhaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/diario': typeof DiarioRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/pets': typeof PetsRoute
  '/sobre': typeof SobreRoute
  '/doadores/$doadorId': typeof DoadoresDoadorIdRoute
  '/vaquinhas/$vaquinhaId': typeof VaquinhasVaquinhaIdRoute
  '/doadores/': typeof DoadoresIndexRoute
  '/vaquinhas/': typeof VaquinhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/diario': typeof DiarioRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/pets': typeof PetsRoute
  '/sobre': typeof SobreRoute
  '/doadores/$doadorId': typeof DoadoresDoadorIdRoute
  '/vaquinhas/$vaquinhaId': typeof VaquinhasVaquinhaIdRoute
  '/doadores': typeof DoadoresIndexRoute
  '/vaquinhas': typeof VaquinhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desaparecidos': typeof DesaparecidosRoute
  '/diario': typeof DiarioRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/pets': typeof PetsRoute
  '/sobre': typeof SobreRoute
  '/doadores/$doadorId': typeof DoadoresDoadorIdRoute
  '/vaquinhas/$vaquinhaId': typeof VaquinhasVaquinhaIdRoute
  '/doadores/': typeof DoadoresIndexRoute
  '/vaquinhas/': typeof VaquinhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/chat'
    | '/configuracoes'
    | '/desaparecidos'
    | '/diario'
    | '/favoritos'
    | '/perfil'
    | '/pets'
    | '/sobre'
    | '/doadores/$doadorId'
    | '/vaquinhas/$vaquinhaId'
    | '/doadores/'
    | '/vaquinhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/chat'
    | '/configuracoes'
    | '/desaparecidos'
    | '/diario'
    | '/favoritos'
    | '/perfil'
    | '/pets'
    | '/sobre'
    | '/doadores/$doadorId'
    | '/vaquinhas/$vaquinhaId'
    | '/doadores'
    | '/vaquinhas'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/chat'
    | '/configuracoes'
    | '/desaparecidos'
    | '/diario'
    | '/favoritos'
    | '/perfil'
    | '/pets'
    | '/sobre'
    | '/doadores/$doadorId'
    | '/vaquinhas/$vaquinhaId'
    | '/doadores/'
    | '/vaquinhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ChatRoute: typeof ChatRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DesaparecidosRoute: typeof DesaparecidosRoute
  DiarioRoute: typeof DiarioRoute
  FavoritosRoute: typeof FavoritosRoute
  PerfilRoute: typeof PerfilRoute
  PetsRoute: typeof PetsRoute
  SobreRoute: typeof SobreRoute
  DoadoresDoadorIdRoute: typeof DoadoresDoadorIdRoute
  VaquinhasVaquinhaIdRoute: typeof VaquinhasVaquinhaIdRoute
  DoadoresIndexRoute: typeof DoadoresIndexRoute
  VaquinhasIndexRoute: typeof VaquinhasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desaparecidos': {
      id: '/desaparecidos'
      path: '/desaparecidos'
      fullPath: '/desaparecidos'
      preLoaderRoute: typeof DesaparecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doadores/': {
      id: '/doadores/'
      path: '/doadores'
      fullPath: '/doadores/'
      preLoaderRoute: typeof DoadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doadores/$doadorId': {
      id: '/doadores/$doadorId'
      path: '/doadores/$doadorId'
      fullPath: '/doadores/$doadorId'
      preLoaderRoute: typeof DoadoresDoadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaquinhas/': {
      id: '/vaquinhas/'
      path: '/vaquinhas'
      fullPath: '/vaquinhas/'
      preLoaderRoute: typeof VaquinhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaquinhas/$vaquinhaId': {
      id: '/vaquinhas/$vaquinhaId'
      path: '/vaquinhas/$vaquinhaId'
      fullPath: '/vaquinhas/$vaquinhaId'
      preLoaderRoute: typeof VaquinhasVaquinhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ChatRoute: ChatRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DesaparecidosRoute: DesaparecidosRoute,
  DiarioRoute: DiarioRoute,
  FavoritosRoute: FavoritosRoute,
  PerfilRoute: PerfilRoute,
  PetsRoute: PetsRoute,
  SobreRoute: SobreRoute,
  DoadoresDoadorIdRoute: DoadoresDoadorIdRoute,
  VaquinhasVaquinhaIdRoute: VaquinhasVaquinhaIdRoute,
  DoadoresIndexRoute: DoadoresIndexRoute,
  VaquinhasIndexRoute: VaquinhasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
